services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: backend_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql


  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: backend_db_migration
    depends_on:
      - db
    entrypoint: ["/bin/bash", "-c", "./wait-for-it.sh db:5432 -- migrate -path /migrations -database \"postgres://postgres:postgres@db:5432/mydb?sslmode=disable\" goto 21 -verbose up"]
    volumes:
      - ./business/db/migrations:/migrations
      - ./wait-for-it.sh:/wait-for-it.sh

volumes:
  backend_postgres_data: {}
