// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID     `json:"id"`
	FirstName    string        `json:"firstName"`
	LastName     string        `json:"lastName"`
	Email        string        `json:"email"`
	Phone        string        `json:"phone"`
	Gender       sql.NullInt32 `json:"gender"`
	ProfilePhoto string        `json:"profilePhoto"`
	Status       sql.NullInt32 `json:"status"`
	IsDeleted    sql.NullBool  `json:"isDeleted"`
}

type Learner struct {
	AccountID uuid.UUID `json:"accountId"`
	SchoolID  uuid.UUID `json:"schoolId"`
}

type School struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

type Staff struct {
	AccountID uuid.UUID `json:"accountId"`
	Role      int16     `json:"role"`
	CreatedBy uuid.UUID `json:"createdBy"`
}
