// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlc

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id FROM "accounts"
`

func (q *Queries) GetAccount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAccount)
	var id int64
	err := row.Scan(&id)
	return id, err
}
