// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertSubjectSkill implements pgx.CopyFromSource.
type iteratorForInsertSubjectSkill struct {
	rows                 []InsertSubjectSkillParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSubjectSkill) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSubjectSkill) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SubjectID,
		r.rows[0].SkillID,
	}, nil
}

func (r iteratorForInsertSubjectSkill) Err() error {
	return nil
}

func (q *Queries) InsertSubjectSkill(ctx context.Context, arg []InsertSubjectSkillParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subject_skills"}, []string{"id", "subject_id", "skill_id"}, &iteratorForInsertSubjectSkill{rows: arg})
}
