// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: districts.sql

package sqlc

import (
	"context"
)

const getDistrictsByProvince = `-- name: GetDistrictsByProvince :many
SELECT id, name, province_id FROM districts WHERE districts.province_id = $1::integer ORDER BY id
`

func (q *Queries) GetDistrictsByProvince(ctx context.Context, provinceID int32) ([]District, error) {
	rows, err := q.db.QueryContext(ctx, getDistrictsByProvince, provinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []District
	for rows.Next() {
		var i District
		if err := rows.Scan(&i.ID, &i.Name, &i.ProvinceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
