// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: learner_attendances.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const generateLearnerAttendance = `-- name: GenerateLearnerAttendance :exec
INSERT INTO learner_attendances(id, class_learner_id, slot_id)
SELECT uuid_generate_v4(), $1, $2::uuid
`

type GenerateLearnerAttendanceParams struct {
	ClassLearnerID uuid.UUID `db:"class_learner_id" json:"classLearnerId"`
	SlotID         uuid.UUID `db:"slot_id" json:"slotId"`
}

func (q *Queries) GenerateLearnerAttendance(ctx context.Context, arg GenerateLearnerAttendanceParams) error {
	_, err := q.db.Exec(ctx, generateLearnerAttendance, arg.ClassLearnerID, arg.SlotID)
	return err
}
