// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID           string        `json:"id"`
	FirstName    string        `json:"firstName"`
	LastName     string        `json:"lastName"`
	Email        string        `json:"email"`
	Phone        string        `json:"phone"`
	Gender       sql.NullInt32 `json:"gender"`
	ProfilePhoto string        `json:"profilePhoto"`
	Status       sql.NullInt32 `json:"status"`
	IsDeleted    sql.NullBool  `json:"isDeleted"`
}

type District struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	ProvinceID int32  `json:"provinceId"`
}

type Learner struct {
	AccountID string    `json:"accountId"`
	SchoolID  uuid.UUID `json:"schoolId"`
}

type Province struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type School struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
	DistrictID int32     `json:"districtId"`
}

type Staff struct {
	AccountID string `json:"accountId"`
	Role      int16  `json:"role"`
	CreatedBy string `json:"createdBy"`
}
