// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skills.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getSkillsByIds = `-- name: GetSkillsByIds :many
SELECT id, name FROM skills WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetSkillsByIds(ctx context.Context, skillIds []uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillsByIds, skillIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsBySubjectId = `-- name: GetSkillsBySubjectId :many
SELECT s.id, s.name
FROM skills s
JOIN subject_skills ss ON ss.skill_id = s.id
WHERE ss.subject_id = $1
`

func (q *Queries) GetSkillsBySubjectId(ctx context.Context, subjectID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillsBySubjectId, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
