// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skills.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getSkillsByIDs = `-- name: GetSkillsByIDs :many
SELECT id, name FROM skills WHERE id IN($1::uuid[])
`

func (q *Queries) GetSkillsByIDs(ctx context.Context, skillIds []uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillsByIDs, skillIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
