// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specialization_skills.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSpecializationSkills = `-- name: CreateSpecializationSkills :exec
INSERT INTO specialization_skills (specialization_id, skill_id)
SELECT $1::uuid, unnest($2::uuid[])
`

type CreateSpecializationSkillsParams struct {
	SpecializationID uuid.UUID   `db:"specialization_id" json:"specializationId"`
	SkillIds         []uuid.UUID `db:"skill_ids" json:"skillIds"`
}

func (q *Queries) CreateSpecializationSkills(ctx context.Context, arg CreateSpecializationSkillsParams) error {
	_, err := q.db.Exec(ctx, createSpecializationSkills, arg.SpecializationID, arg.SkillIds)
	return err
}
