// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specializations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSpecialization = `-- name: CreateSpecialization :exec
INSERT INTO specializations (id, name, code, time_amount, image_link, description, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type CreateSpecializationParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Code        string    `db:"code" json:"code"`
	TimeAmount  *float64  `db:"time_amount" json:"timeAmount"`
	ImageLink   *string   `db:"image_link" json:"imageLink"`
	Description *string   `db:"description" json:"description"`
	CreatedBy   string    `db:"created_by" json:"createdBy"`
}

func (q *Queries) CreateSpecialization(ctx context.Context, arg CreateSpecializationParams) error {
	_, err := q.db.Exec(ctx, createSpecialization,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.TimeAmount,
		arg.ImageLink,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}
