// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specialization_subjects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSpecializationSubjects = `-- name: CreateSpecializationSubjects :exec
INSERT INTO specialization_subjects (specialization_id, subject_id, created_by)
SELECT $1::uuid, unnest($2::uuid[]), $3::varchar
`

type CreateSpecializationSubjectsParams struct {
	SpecializationID uuid.UUID   `db:"specialization_id" json:"specializationId"`
	SubjectIds       []uuid.UUID `db:"subject_ids" json:"subjectIds"`
	CreatedBy        string      `db:"created_by" json:"createdBy"`
}

func (q *Queries) CreateSpecializationSubjects(ctx context.Context, arg CreateSpecializationSubjectsParams) error {
	_, err := q.db.Exec(ctx, createSpecializationSubjects, arg.SpecializationID, arg.SubjectIds, arg.CreatedBy)
	return err
}
