// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subject_skills.sql

package sqlc

import (
	"github.com/google/uuid"
)

type InsertSubjectSkillParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	SubjectID uuid.UUID `db:"subject_id" json:"subjectId"`
	SkillID   uuid.UUID `db:"skill_id" json:"skillId"`
}
