INSERT INTO schools (id, name, address)
VALUES
(uuid_generate_v4 (), 'Trường Phổ thông Năng Khiếu, Đại học Quốc gia TP.HCM', '153 Nguyễn Chí Thanh, Phường 9, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Phổ thông Năng Khiếu, Đại học Quốc gia TP.HCM', 'Khu đô thị Đại học Quốc gia, Phường Linh Trung, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT chuyên Trần Đại Nghĩa', '2/6A Lương Định Của, Phường An Khánh, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT chuyên Lê Hồng Phong', '235 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Gia Định', '44 Võ Oanh, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Mạc Đĩnh Chi', '4 Tân Hòa Đông, Phường 13, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hữu Huân', '544 Cách Mạng Tháng Tám, Phường 4, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Thượng Hiền', '235 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Năng khiếu Thể dục Thể thao TP.HCM', '43 Điện Biên Phủ, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Năng khiếu Thể dục Thể thao Nguyễn Thị Định', '215 Hoàng Ngân, Phường 16, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Phổ thông Năng khiếu Thể thao Olympic – Đại học Thể dục Thể thao TPHCM', 'Phường Linh Trung, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Năng khiếu Thể dục Thể thao Bình Chánh', 'A10/3D Mai Bá Hương, Xã Lê Minh Xuân, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bùi Thị Xuân', '73 Bùi Thị Xuân, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trưng Vương', '3 Nguyễn Bỉnh Khiêm, Phường Bến Nghé, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Ernst Thälmann', '8 Trần Hưng Đạo, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lương Thế Vinh', '131 Cô Bắc, Phường Cô Giang, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lê Quý Đôn', '10 Nguyễn Thị Minh Khai, Phường Võ Thị Sáu, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Thị Minh Khai', '275 Điện Biên Phủ, Phường Võ Thị Sáu, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Marie Curie', '159 Nam Kỳ Khởi Nghĩa, Phường Võ Thị Sáu, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Thị Diệu', '12 Trần Quốc Toản, Phường Võ Thị Sáu, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lê Thị Hồng Gấm', '147 Pasteur, Phường Võ Thị Sáu, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Trãi', 'Số 364 Nguyễn Tất Thành, Phường 18, Quận 4, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hữu Thọ', 'Số 2 Bến Vân Đồn, Phường 13, Quận 4, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hùng Vương', 'Số 124 Hồng Bàng, Phường 12, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Trung học Thực hành Sài Gòn', 'Số 220 Trần Bình Trọng, Phường 4, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Trung học Thực hành - Đại học Sư phạm TP.HCM', 'Số 280 An Dương Vương, Phường 4, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Khai Nguyên', 'Số 225 Nguyễn Tri Phương, Phường 9, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Hữu Trang', 'Số 276 Trần Hưng Đạo B, Phường 11, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Phú', 'Số 102 Trần Văn Kiểu, Phường 10, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Tất Thành', 'Số 249 Nguyễn Văn Luông, Phường 11, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phạm Phú Thứ', 'Số 425 - 435 Gia Phú, Phường 3, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Ngô Quyền', 'Số 1360 Huỳnh Tấn Phát, Phường Phú Mỹ, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lê Thánh Tôn', 'Số 124 Đường 17, Phường Tân Kiểng, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Nam Sài Gòn', 'Khu A - Đô thị mới Nam Sài Gòn, Phường Tân Phú, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tân Phong', 'Số 15F Nguyễn Văn Linh, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lương Văn Can', 'Số 173 Phạm Hùng, Phường 4, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Ngô Gia Tự', 'Số 360E Bến Bình Đông, Phường 15, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tạ Quang Bửu', 'Số 909 Tạ Quang Bửu, Phường 5, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Văn Linh', 'Số 2 Đường 3154 Phạm Thế Hiển, Phường 7, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Võ Văn Kiệt', 'Số 629 Bến Bình Đông, Phường 13, Quận 8, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn An Ninh', 'Số 93 Trần Nhân Tôn, Phường 2, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Sương Nguyệt Anh', 'Số 249 Hòa Hảo, Phường 2, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Du', 'Số XX1 Đồng Nai - Cư xá Bắc Hải, Phường 15, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Khuyến', 'Số 50 Thành Thái, Phường 12, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Diên Hồng', 'Số 11 Thành Thái, Phường 14, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nam Kỳ Khởi Nghĩa', 'Số 269/8 Nguyễn Thị Nhỏ, Phường 16, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hiền', 'Số 03 Dương Đình Nghệ, Phường 8, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Quang Khải', 'Số 343D Lạc Long Quân, Phường 5, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Võ Trường Toản', 'Số 482 Nguyễn Thị Đặng, Phường Hiệp Thành, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trường Chinh', 'Số 01 DN 11, Phường Tân Hưng Thuận, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thạnh Lộc', 'Số 116 Nguyễn Thị Sáu,Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT An Lạc', 'Số 595 Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hữu Cảnh', 'Số 845 Hương Lộ 2, Phường Bình Trị Đông A, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Tân', 'Số 117/4H Hồ Văn Long, Phường Tân Tạo, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Hưng Hòa', 'Số 79/19 Đường số 4, Phường Bình Hưng Hòa, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Vĩnh Lộc', 'Số 87 Đường số 3, Phường Bình Hưng Hòa B, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Võ Thị Sáu', 'Số 95 Lê Văn Duyệt, Phường 3, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phan Đăng Lưu', 'Số 27 Nguyễn Văn Đậu, Phường 6, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hoàng Hoa Thám', 'Số 6 Hoàng Hoa Thám, Phường 7, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thanh Đa', 'Số 186 Nguyễn Xí, Phường 26, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Văn Giàu', 'Số 203/40 Đặng Thùy Trâm, Phường 13, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Trung Trực', 'Số 9/168 Lê Đức Thọ, Phường 15, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Gò Vấp', 'Số 90A Nguyễn Thái Sơn, Phường 3, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Công Trứ', 'Số 97 Quang Trung, Phường 8, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Hưng Đạo', 'Số 88/955E Lê Đức Thọ, Phường 6, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phú Nhuận', 'Số 5 Hoàng Minh Giám, Phường 9, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hàn Thuyên', 'Số 37 Đặng Văn Ngữ, Phường 10, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Thái Bình', 'Số 913-915 Lý Thường Kiệt, Phường 9, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Chí Thanh', 'Số 1A Nguyễn Hiến Lê, Phường 13, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Phú', 'Số 18 Lê Thúc Hoạch, Phường Phú Thọ Hòa, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tân Bình', 'Số 19 Hoa Bằng, Phường Tân Sơn Nhì, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tây Thạnh', 'Số 27 Đường C2, Phường Tây Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lê Trọng Tấn', 'Số 5 Đường D2, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thủ Đức', 'Số 166/24 Đặng Văn Bi, Phường Bình Thọ, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thủ Thiêm', 'Số 1 Vũ Tông Phan, Phường An Phú, Quận 2, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Giồng Ông Tố', 'Số 200/10 Nguyễn Thị Định, Phường Bình Trưng Tây, Quận 2 (cũ), TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Huệ', 'Số 13 Đường số 13, Phường Long Thạnh Mỹ, Quận 9 (cũ), TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tam Phú', 'Số 31 Phú Châu, Phường Tam Phú, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phước Long', 'Số 18D Dương Đình Hội, Phường Phước Long B, Quận 9, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Long Trường', 'Số 309 Võ Văn Hát, Phường Long Trường, Quận 9, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hiệp Bình', 'Số 63 Hiệp Bình, Phường Hiệp Bình Phước, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Đào Sơn Tây', 'Số 53/5 Đường 10, Phường Linh Xuân, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Văn Tăng', 'Số 1 - Khu tái định cư Long Bửu, Phường Long Bình, Quận 9, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Linh Trung', 'Số 5 Đường 16, Phường Linh Trung, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Chiểu', 'Số 88B Lê Thị Hoa, Phường Bình Chiểu, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Dương Văn Thì', 'Số 161 Lã Xuân Oai, Phường Tăng Nhơn Phú A, Quận 9 (cũ), TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Chánh', 'Số D17/1D Huỳnh Văn Trí, Xã Bình Chánh, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lê Minh Xuân', 'Số G11/1 Ấp 7, Xã Lê Minh Xuân, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Đa Phước', 'Số D14/410A Quốc lộ 50, Xã Đa Phước, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tân Túc', 'Số C1/3K Bùi Thanh Khiết, Thị trấn Tân Túc, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Vĩnh Lộc B', 'Đường số 3, Khu dân cư Vĩnh Lộc B, Xã Vĩnh Lộc B, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phong Phú', 'Số 2 Đường 14B, KDC Phong Phú 4, Xã Phong Phú, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bình Khánh', 'Đường Rừng Sác, Ấp Bình An, Xã Bình Khánh, Huyện Cần Giờ, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Cần Thạnh', 'Số 346 Duyên Hải, Thị trấn Cần Thạnh, Huyện Cần Giờ, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT An Nghĩa', 'Đường Tam Thôn Hiệp, Ấp An Nghĩa, Xã An Thới Đông, Huyện Cần Giờ, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Thạnh An', 'Ấp Thạnh Hoà, Xã đảo Thạnh An, Huyện Cần Giờ, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Củ Chi', 'Tỉnh lộ 8, Khu phố 1, Thị trấn Củ Chi, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trung Phú', 'Số 1318 Tỉnh lộ 8, Xã Tân Thạnh Đông, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT An Nhơn Tây', 'Số 1290 Tỉnh lộ 7, Xã An Nhơn Tây, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Quang Trung', 'Tỉnh lộ 7, Ấp Phước An, Xã Phước Thạnh, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trung Lập', 'Số 91/3 Trung Lập, Xã Trung Lập Thượng, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phú Hòa', 'Huỳnh Thị Bẳng, Ấp Phú Lợi, Xã Phú Hòa Đông, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Tân Thông Hội', 'Đường Suối Lội, Ấp Bầu Sim, Xã Tân Thông Hội, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lý Thường Kiệt', 'Đường Trần Thị Bốc, Xã Thới Tam Thôn, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hữu Cầu', 'Số 07 Nguyễn Ảnh Thủ, Xã Trung Chánh, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bà Điểm', 'Số 07 Nguyễn Thị Sóc, Xã Bà Điểm, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Hữu Tiến', 'Số 9A Ấp 7, Xã Đông Thạnh, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Văn Cừ', 'Số 100A Nguyễn Văn Bứa, Xã Xuân Thới Thượng, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phạm Văn Sáng', 'Số 26/1C Ấp 3, Xã Xuân Thới Sơn, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hồ Thị Bi', 'Số 32 Tân Hiệp 28, Ấp Tân Thới 3, Xã Tân Hiệp, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Long Thới', 'Số 280 Nguyễn Văn Tạo, Xã Long Thới, Huyện Nhà Bè, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phước Kiển', 'Số 1163 Lê Văn Lương, Xã Phước Kiển, Huyện Nhà Bè, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Dương Văn Dương', 'Số 39 Đường 6, Khu dân cư Phú Gia, Xã Phú Xuân, Huyện Nhà Bè, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học, THCS và THPT Hermann Gmeiner', '697 Tân Sơn, Phường 15, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đăng Khoa', '571 Cô Bắc, Phường Cầu Ông Lãnh, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đăng Khoa', '72 Đặng Văn Ngữ, Phường 10, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nguyễn Bỉnh Khiêm', '28-30 Ngô Quyền, Phường 6, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT An Đông', '91 Nguyễn Chí Thanh, Phường 9, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thăng Long', '114-116 Hải Thượng Lãn Ông, Phường 10, Quận 5. TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thăng Long', '24 Đường 45, Phường 14, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Khai Trí', '133 Nguyễn Trãi, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Văn Lang', '2 - 4 Tân Thành, Phường 12, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Quang Trung Nguyễn Huệ', '223 Nguyễn Tri Phương, Phường 9, Quận 5, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Quang Trung Nguyễn Huệ', '780 Nguyễn Kiệm, Phường 4, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS – THPT Phan Bội Châu', '293-299 Nguyễn Đình Chi, Phường 9, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Quốc Trí', '313 Nguyễn Văn Luông, Phường 12, Quận 6, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Sao Việt', 'Khu dân cư Him Lam, Phường Tân Hưng, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đức Trí', '39/23 Bùi Văn Ba, Phường Tân Thuận Đông, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đức Trí', '742/10 Nguyễn Kiệm, Phường 4, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đinh Thiện Lý', 'Lô P1, khu A, khu đô thị Phú Mỹ Hưng, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Hoàng Gia', '38 Đặng Đại Đô, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Hoàng Gia', '02 đường D2, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nhân Trí', '409 Sư Vạn Hạnh nối dài, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Duy Tân', '106 Nguyễn Giản Thanh, Phường 15, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Vạn Hạnh', '781E Lê Hồng Phong, Phường 12, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Trương Vĩnh Ký', '21 Trịnh Đình Trọng, Phường 5, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Trương Vĩnh Ký', '110 Bành Văn Trân, Phường 7, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Quốc Tuấn', '236/10-236/12 Thái Phiên, Phường 8, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Bắc Sơn', '338/24 Nguyễn Văn Quá, Phường Đông Hưng Thuận, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Bắc Sơn', '371A-B Nguyễn Văn Quá, Phường Đông Hưng Thuận, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Phùng Hưng', '27 Thạnh Lộc 02, Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Lạc Hồng', '2276/5 Quốc lộ 1, Phường Trung Mỹ Tây, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Lạc Hồng', '556/4 Lê Thị Riêng, Phường Thới An, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Việt Âu', '30/2 Quốc lộ 1A, Phường Tân Thới Hiệp, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Ngọc Viễn Đông', '53/1-2-3 Đông Hưng Thuận 2, Phường Tân Hưng Thuận, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hoa Lư', '201 Phan Văn Hớn, Phường Tân Thới Nhất, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hàn Việt', '70 Tân Thới Nhất 8, Phường Tân Thới Nhất, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Đông Dương', '103 Hà Huy Giáp, Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Tuệ Đức', '8 Tân Thới Nhất 17, Phường Tân Thới Nhất, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Mỹ Việt', '95 Phan Văn Hớn, Phường Tân Thới Nhất, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Đông Đô', '12B Nguyễn Hữu Cảnh, Phường 19, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phan Hữu Ích', '480/81A Lê Quang Định, Phường 11, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Sài Gòn', '215D-E, 217 Nơ Trang Long, Phường 12, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Vinschool', '720A Điện Biên Phủ, Phường 22, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Vinschool', '2 Tôn Đức Thắng, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Anh Quốc', '48 Võ Oanh, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Lam Sơn', '451/45 Xô Viết Nghệ Tĩnh, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hồng Hà', '170 Quang Trung, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hồng Hà', '342 Nguyễn Trọng Tuyển, Phường 2, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hồng Hà', '14A Đường 1, Phường 16, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Phạm Ngũ Lão', '528 Phan Văn Trị, Phường 7, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học -  THCS - THPT Sài Gòn - Gia Định', '514 Lê Quang Định, Phường 1, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nguyễn Tri Phương', '112/48 Bùi Quang Lá, Phường 12, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Việt Nhật', '371 Nguyễn Kiệm, Phường 3, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Anh', '160/72 Phan Huy Ích, Phường 12, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Anh', '269A Nguyễn Trọng Tuyển, Phường 10, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lý Thái Tổ', '1/22/2A Nguyễn Oanh, Phường 6, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Lý Thái Tổ', '54/5C Phạm Văn Chiêu, Phường 14, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hưng Đạo', '120/29/24 Thích Quảng Đức, Phường 4, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS – THPT Nguyễn Khuyến', '136 Cộng Hòa, Phường 4, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS – THPT Nguyễn Khuyến', '327 Đường số 3, Phường Hiệp Bình Phước, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Thái Bình', '10 Trương Hoàng Thanh, Phường 12, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Thanh Bình', '192/12 Nguyễn Thái Bình, Phường 12, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Việt Thanh', '261 Cộng Hòa, Phường 13, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Việt Mỹ Anh', '806 Âu Cơ, Phường 14, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Bắc Ái', '187 Gò Cầm Đệm, Phường 10, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hai Bà Trưng', '51/4 Nguyễn Thị Nhỏ, Phường 9, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Thủ Khoa Huân', '481/8 Trường Chinh, Phường 14, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Thái Bình Dương', '125 Bạch Đằng, Phường 2, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đào Duy Anh', '23 - 25 Nguyễn Văn Vịnh, Phường Hiệp Tân, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hồng Đức', 'Số 8 Hồ Đắc Di, Phường Tây Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hồng Đức', '118 Nam Hòa, Phường Phước Long A, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nhân Văn', '17 Sơn Kỳ, Phường Sơn Kỳ, Quận Tân Phú., TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Nguyễn Trãi', '380 Văn Cao, Phú Thọ Hòa, Quận Tân phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trí Đức', '5 Thoại Ngọc Hầu, Phường Hòa Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trí Đức', 'Khu phố 5, đường DC6, KCN Tân Bình, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Hòa Bình', '152 Nguyễn Duy Dương, Phường 3, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Hòa Bình', '69 Trịnh Đình Thảo, Phường Hòa Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Khai Minh', '410 Tân Kỳ Tân Quý, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nam Việt', '25, 21/1-3, 23/7-9 Dương Đức Hiền, Phường Tây Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nam Việt', '17/15B, 11C Phan Văn Hớn, Phường Tân Thới Nhất, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nam Việt', '599A Lê Văn Thọ, Phường 14, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Vĩnh Viễn', '73/7 Lê Trọng Tấn, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Lê Thánh Tông', '22 Bờ Bao Tân Thắng, Phường Sơn Kỳ, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Minh Đức', '277 Tân Quý, Phường Tân Quý, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Tre Việt', '42/39 - 42/41 Huỳnh Thiên Lộc, Phường Hòa Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Tre Việt', '26/25M, 26/25N, 26/25P Xã Xuân Thới Đông, Huyện Hóc Môn, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Tre Việt', '3/5 và 007 Tân Chánh Hiệp 1, Phường Tân Chánh Hiệp, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Đinh Tiên Hoàng', '85 Chế Lan Viên, Phường Tây Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trần Cao Vân', '126 Tô Hiệu, Phường Hiệp Tân, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trần Cao Vân', '525 Phan Văn Trị, Phường 5, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trần Cao Vân', '512/22A Thống Nhất, Phường 6, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Trần Cao Vân', '88/20/20 Thạnh Lộc 40, Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Nam Úc', '300 Hòa Bình, Phường Hiệp Tân, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Tân Phú', '519 Kênh Tân Hóa, Phường Hòa Thạnh, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Đông Á', '108 Lê Thúc Hoạch, Phường Phú Thọ Hòa, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT An Dương Vương', '51/4 Hòa Bình, Phường Tân Thới Hòa, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Huỳnh Thúc Kháng', '108 Nguyễn Quý Anh, Phường Tân Sơn Nhì, Quận Tân Phú, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Ngôi Sao', 'Đường số 18, Phường Bình Trị Đông B, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Phan Châu Trinh', '12 Đường 23, Phường Bình Trị Đông B, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phú Lâm', '721 Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Trần Nhân Tông', '200 Tân Hòa Đông, Phường Bình Trị Đông A, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Chu Văn An', 'Số 7 Đường số 1, Phường Bình Hưng Hòa, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Trí Tuệ Việt', '79 Đường số 3, KDC Vĩnh Lộc, Phường Bình Hưng Hòa B, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Hàm Nghi', '911 QL1A, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Phương Nam', 'KP6, Phường Trường Thọ, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Ngô Thời Nhiệm', '65D Hồ Bá Phấn, Phường Phước Long A, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Ngô Thời Nhiệm', '2A Phan Văn Trị, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Ngô Thời Nhiệm', '73/8 Võ Văn Kiệt, KP 2, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Ngô Thời Nhiệm', '78/30B Hồ Bá Phấn, Phường Phước Long A, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hoa Sen', '26 Phan Châu Trinh, Phường Hiệp Phú, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hoa Sen', '674/7 Xa lộ Hà Nội, Phường Hiệp Phú, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THCS - THPT Hoa Sen', '190 Võ Văn Ngân, Phường Hiệp Thọ, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Bách Việt', '653 Quốc lộ 13, KP3, Phường Hiệp Bình Phước, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT Chiến Thắng', '83A Bùi Thị He, Thị trấn Củ Chi, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Thiếu Sinh Quân', 'Ấp Bến Đình, Xã Nhuận Đức, Huyện Củ Chi, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '4 Thái Văn Lung, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '149-151-153-155 Võ Oanh, Phường 25, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '226A Pasteur, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '29-31 Trần Nhật Duật, Phường Tân Định, Quận 1, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '18A2 Cộng Hòa, Phường 12, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '177Bis Cao Thắng, Phường 12, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Á Châu', '117/11-19, 179-185 Nguyễn Văn Hướng, Phường Thảo Điền, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Nam Mỹ', '69/68 Đặng Thùy Trâm, Phường 13, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Quốc tế Nam Mỹ', '360D Bến Vân Đồn, Phường 1, Quận 4, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Hệ thống Trường Song ngữ Quốc tế EMASI', 'Số 147 đường số 8, Khu Dân cư Nam Long, Phường Tân Thuận Đông, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Hệ thống Trường Song ngữ Quốc tế EMASI', 'Số 2 đường số 5, Khu Đô thị Vạn Phúc, Phường Hiệp Bình Phước, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '594 Ba Tháng Hai, Phường 14, Quận 10, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '202 Hoàng Văn Thụ, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '1 Đường 20 - Khu Him Lam, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '168 Phan Văn Trị, Quận Gò Vấp, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '99 Nguyễn Thị Thập, Phường Tân Phú, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Úc', '10 Mai Chí Thọ - Khu Đô thị mới Thủ Thiêm, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Quốc tế Thành phố Hồ Chí Minh', '28 Võ Trường Toản, Phường An Phú, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Quốc tế Việt Nam - Phần Lan', '19 Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Quốc tế Thành phố Hồ Chí Minh - Học viện Mỹ', '16 Võ Trường Toản, Phường An Phú, TP. Thủ Đức, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Việt Mỹ', '19A Cộng Hòa, Phường 12, Quận Tân Bình, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Quốc tế Nam Sài Gòn', '78 Nguyễn Đức Cảnh, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Phổ thông Song ngữ Quốc tế Wellspring Saigon (Tiểu học - THCS - THPT Mùa Xuân)', '92 Nguyễn Hữu Cảnh, Quận Bình Thạnh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Tây Úc', '657 Lý Chính Thắng, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học, THCS - THPT Quốc Tế', '305 Nguyễn Trọng Tuyển, Phường 10, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường THPT quốc tế Việt Úc', '184/7 Lê Văn Sỹ, Phường 10, Quận Phú Nhuận, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Quốc tế Hoa Kỳ', '286 Lãnh Binh Thăng, Phường 11, Quận 11, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT Albert Einstein', '16 đường số 12, KDC 13C, Xã Phong Phú, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường Tiểu học - THCS - THPT quốc tế Bắc Mỹ', 'KDC Him Lam, Xã Bình Hưng, Huyện Bình Chánh, TP. Hồ Chí Minh.'),
(uuid_generate_v4 (), 'Trường phổ thông IVS', 'Số 27 TL02, Khu phố 3A, Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh.');









